name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/iconamoon-home-bold.png
    - assets/page-1/images/ci-hamburger-md.png
    - assets/page-1/images/vector.png
    - assets/page-1/images/line-1.png
    - assets/page-1/images/vector-rjb.png
    - assets/page-1/images/iconamoon-profile-circle-fill.png
    - assets/page-1/images/vector-d29.png
    - assets/page-1/images/tabler-message.png
    - assets/page-1/images/vector-LNu.png
    - assets/page-1/images/ellipse-13.png
    - assets/page-1/images/ellipse-13-ZZ3.png
    - assets/page-1/images/ci-hamburger-md-7kD.png
    - assets/page-1/images/tabler-message-ZV3.png
    - assets/page-1/images/line-1-CWm.png
    - assets/page-1/images/ci-hamburger-md-Ae5.png
    - assets/page-1/images/line-1-tM7.png
    - assets/page-1/images/line-2.png
    - assets/page-1/images/akar-icons-schedule.png
    - assets/page-1/images/ci-hamburger-md-thX.png
    - assets/page-1/images/line-1-uuK.png
    - assets/page-1/images/line-2-nrm.png
    - assets/page-1/images/line-4.png
    - assets/page-1/images/vector-fkd.png
    - assets/page-1/images/zondicons-add-outline.png
    - assets/page-1/images/ci-hamburger-md-FeH.png
    - assets/page-1/images/tabler-message-c4q.png
    - assets/page-1/images/akar-icons-schedule-6QR.png
    - assets/page-1/images/vector-cgR.png
    - assets/page-1/images/group.png
    - assets/page-1/images/iconamoon-profile-circle-fill-ULZ.png
    - assets/page-1/images/ci-hamburger-md-XRK.png
    - assets/page-1/images/line-3.png
    - assets/page-1/images/ellipse-13-r4q.png
    - assets/page-1/images/zondicons-add-outline-fLM.png
    - assets/page-1/images/group-hnZ.png
    - assets/page-1/images/akar-icons-schedule-APB.png
    - assets/page-1/images/ellipse-13-J4h.png
    - assets/page-1/images/vector-QyX.png
    - assets/page-1/images/zondicons-add-outline-38M.png
    - assets/page-1/images/akar-icons-schedule-QMF.png
    - assets/page-1/images/iconamoon-home-bold-meR.png
    - assets/page-1/images/vector-EXT.png
    - assets/page-1/images/mdi-triangle-QS5.png
    - assets/page-1/images/mdi-triangle.png
    - assets/page-1/images/iconamoon-profile-circle-fill-TSH.png
    - assets/page-1/images/iconamoon-profile-circle-fill-Bmb.png
    - assets/page-1/images/iconamoon-profile-circle-fill-xQy.png
    - assets/page-1/images/vector-WSV.png
    - assets/page-1/images/group-uDj.png
    - assets/page-1/images/auto-group-5kyt.png
    - assets/page-1/images/iconamoon-profile-circle-fill-b77.png
    - assets/page-1/images/vector-beq.png
    - assets/page-1/images/mdi-triangle-yVb.png
    - assets/page-1/images/iconamoon-home-bold-wSR.png
    - assets/page-1/images/tabler-message-WEd.png
    - assets/page-1/images/iconamoon-profile-circle-fill-GDo.png
    - assets/page-1/images/zondicons-add-outline-BrZ.png
    - assets/page-1/images/mdi-triangle-xMX.png
    - assets/page-1/images/vector-3Ny.png
    - assets/page-1/images/iconamoon-profile-circle-fill-geD.png
    - assets/page-1/images/rectangle-27.png
    - assets/page-1/images/vector-dSH.png
    - assets/page-1/images/tabler-message-uSy.png
    - assets/page-1/images/vector-F6q.png
    - assets/page-1/images/iconamoon-profile-circle-fill-QA5.png
    - assets/page-1/images/group-94M.png
    - assets/page-1/images/icon-magnifying-glass.png
    - assets/page-1/images/iconamoon-profile-circle-fill-6Fj.png
    - assets/page-1/images/vector-wp5.png
    - assets/page-1/images/line-1-8Nm.png
    - assets/page-1/images/zondicons-add-outline-tVf.png
    - assets/page-1/images/icon-magnifying-glass-1ms.png
    - assets/page-1/images/line-1-B3P.png
    - assets/page-1/images/iconamoon-profile-circle-fill-RdB.png
    - assets/page-1/images/auto-group-sdzu.png
    - assets/page-1/images/ellipse-13-T7F.png
    - assets/page-1/images/iconamoon-profile-circle-fill-SyP.png
    - assets/page-1/images/auto-group-ckas.png
    - assets/page-1/images/vector-7Pw.png
    - assets/page-1/images/auto-group-d9b9.png
    - assets/page-1/images/ci-hamburger-md-qdb.png
    - assets/page-1/images/vector-bfw.png
    - assets/page-1/images/ci-hamburger-md-G5F.png
    - assets/page-1/images/icon-magnifying-glass-v5F.png
    - assets/page-1/images/iconamoon-profile-circle-fill-rph.png
    - assets/page-1/images/icon-person.png
    - assets/page-1/images/icon-person-zk9.png
    - assets/page-1/images/ellipse-8.png
    - assets/page-1/images/ellipse-8-529.png
    - assets/page-1/images/zondicons-add-outline-KdB.png
    - assets/page-1/images/group-rmX.png
    - assets/page-1/images/ellipse-8-Ynm.png
    - assets/page-1/images/ellipse-8-VtM.png
    - assets/page-1/images/iconamoon-profile-circle-fill-zkZ.png
    - assets/page-1/images/ellipse-13-Mxu.png
    - assets/page-1/images/vector-yHT.png
    - assets/page-1/images/icon-person-oBo.png
    - assets/page-1/images/vector-WbK.png
    - assets/page-1/images/akar-icons-schedule-6Uy.png
    - assets/page-1/images/icon-person-Ns3.png
    - assets/page-1/images/vector-JmF.png
    - assets/page-1/images/iconamoon-home-bold-yN9.png
    - assets/page-1/images/ellipse-8-5rR.png
    - assets/page-1/images/ellipse-13-qqb.png
    - assets/page-1/images/ellipse-13-Qdo.png
    - assets/page-1/images/group-3PF.png
    - assets/page-1/images/iconamoon-home-bold-9BP.png
    - assets/page-1/images/icon-person-H2h.png
    - assets/page-1/images/iconamoon-home-bold-ZgM.png
    - assets/page-1/images/auto-group-a1cp.png
    - assets/page-1/images/icon-person-sFX.png
    - assets/page-1/images/ellipse-8-ybw.png
    - assets/page-1/images/ellipse-8-dwP.png
    - assets/page-1/images/zondicons-add-outline-Pff.png
    - assets/page-1/images/akar-icons-schedule-ZKF.png
    - assets/page-1/images/icon-person-VvH.png
    - assets/page-1/images/rectangle-27-3B7.png
    - assets/page-1/images/ellipse-8-Keq.png
    - assets/page-1/images/icon-person-TFF.png
    - assets/page-1/images/image-1.png
    - assets/page-1/images/auto-group-trcw.png
    - assets/page-1/images/ellipse-8-wUD.png
    - assets/page-1/images/icon-person-Uvd.png
    - assets/page-1/images/group-doX.png
    - assets/page-1/images/akar-icons-schedule-tNV.png
    - assets/page-1/images/icon-person-pX3.png
    - assets/page-1/images/akar-icons-schedule-Aau.png
    - assets/page-1/images/pepicons-pop-pen.png
    - assets/page-1/images/icon-magnifying-glass-6xH.png
    - assets/page-1/images/iconamoon-profile-circle-fill-3cd.png
    - assets/page-1/images/icon-person-c9w.png
    - assets/page-1/images/auto-group-8lnp.png
    - assets/page-1/images/ellipse-8-qPX.png
    - assets/page-1/images/icon-person-g9F.png
    - assets/page-1/images/rectangle-22.png
    - assets/page-1/images/zondicons-add-outline-cHo.png
    - assets/page-1/images/iconamoon-home-bold-Aq7.png
    - assets/page-1/images/pepicons-pop-pen-Uqo.png
    - assets/page-1/images/iconamoon-home-bold-3e1.png
    - assets/page-1/images/group-GyF.png
    - assets/page-1/images/akar-icons-schedule-E9P.png
    - assets/page-1/images/iconamoon-profile-circle-fill-eLq.png
    - assets/page-1/images/ellipse-8-Sg1.png
    - assets/page-1/images/tabler-message-BQu.png
    - assets/page-1/images/pepicons-pop-pen-TtD.png
    - assets/page-1/images/vector-6RP.png
    - assets/page-1/images/vector-UCy.png
    - assets/page-1/images/ellipse-13-mSy.png
    - assets/page-1/images/iconamoon-profile-circle-fill-82d.png
    - assets/page-1/images/auto-group-8rx5.png
    - assets/page-1/images/zondicons-add-outline-y93.png
    - assets/page-1/images/zondicons-add-outline-rzm.png
    - assets/page-1/images/tabler-message-UdP.png
    - assets/page-1/images/tabler-message-zqw.png
    - assets/page-1/images/zondicons-add-outline-ucd.png
    - assets/page-1/images/zondicons-add-outline-cSV.png
    - assets/page-1/images/image-1-VcV.png
    - assets/page-1/images/group-4Fb.png
    - assets/page-1/images/typcn-arrow-back-outline.png
    - assets/page-1/images/group-kAD.png
    - assets/page-1/images/image-2.png
    - assets/page-1/images/image-2-FyB.png
    - assets/page-1/images/ellipse-13-qnH.png
    - assets/page-1/images/image-2-jp5.png
    - assets/page-1/images/tabler-message-DDT.png
    - assets/page-1/images/iconamoon-home-bold-pky.png
    - assets/page-1/images/ellipse-8-Pe1.png
    - assets/page-1/images/vector-sBw.png
    - assets/page-1/images/vector-Dn9.png
    - assets/page-1/images/akar-icons-schedule-Xuj.png
    - assets/page-1/images/typcn-arrow-back-outline-2LZ.png
    - assets/page-1/images/tabler-message-31s.png
    - assets/page-1/images/image-2-7jX.png
    - assets/page-1/images/iconamoon-home-bold-zi5.png
    - assets/page-1/images/vector-U4h.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
